sudo: false
language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "iojs-1"
  - "iojs-2"
script: "npm install && npm test"
before_install:
  - git submodule update --init --recursive
  - ruby -e "\`npm i -g npm\` if '`npm -v`'<'2.0.0'"
notifications:
  email:
    recipients:
      - z@apiary.io
    on_success: change
    on_failure: always
  hipchat:
    rooms:
      secure: "ZRKSctculEtR03uTxeUjWxQ8lDeC3v7hJJrmPS7JDGPBlzpzlJau1NHu3Zex\nkKWmKHH29t6otZ5tAWF3THDdUssk5VbIRMCpoEEVMJeHuBZijje7nwk2JZR/\ncPwNsIZ4keaAxujh9BBWC0i+PbkrTRxhrzIHTntawInL33ZQP9Q="
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
